"use client";

import ProjectWorkspace from "../components/ProjectWorkspace";
import {
  RE_CATEGORIES,
  RE_CLASSIFICATIONS,
  RE_EXTENSION_MODALITIES,
  RE_FUNDING_SOURCES,
  RE_RESEARCH_CATEGORIES,
  RE_STATUSES,
} from "@/lib/projectModules";

/* Research & Extension monitoring page — configuration for the shared
   ProjectWorkspace component. */

const BADGE_CLASSES = {
  Research: "bg-indigo-100 text-indigo-700",
  Extension: "bg-teal-100 text-teal-700",
};

const CATEGORY_OPTIONS = [
  ...RE_RESEARCH_CATEGORIES.filter((option) => option !== "Others"),
  ...RE_EXTENSION_MODALITIES.filter((option) => option !== "Others"),
  "Others",
];

const CONFIG = {
  title: "Research & Extension Projects",
  subtitle:
    "Track research studies and extension programs filed by the Research & Extension Office.",
  apiBase: "/api/re-extension-project",
  badgeField: "classification",
  badgeClasses: BADGE_CLASSES,
  badgeLabel: "Classification",
  statuses: RE_STATUSES,
  budgetField: "budget",
  showLeader: true,
  emptyHint:
    "Create the first Research or Extension project to start monitoring it here.",
  createDefaults: {},
  filters: [
    { key: "category", label: "Category", options: CATEGORY_OPTIONS },
    { key: "funding_source", label: "Funding", options: RE_FUNDING_SOURCES },
  ],
  detailSections: [
    {
      title: "Project Information",
      fields: [
        { key: "category", label: "Category / Modality" },
        { key: "research_agenda", label: "Research Agenda / Thrust" },
        { key: "objectives", label: "Objectives", kind: "array" },
        {
          key: "beneficiaries",
          label: "Beneficiaries / Target Sectors",
          kind: "array",
        },
        { key: "partner_agency", label: "Partner Agency" },
        { key: "delivery_site", label: "Delivery Site" },
        { key: "expected_outputs", label: "Expected Outputs", kind: "array" },
        {
          key: "responsible_office",
          label: "Responsible Office",
          kind: "array",
        },
      ],
    },
    {
      title: "Funding",
      fields: [
        { key: "funding_source", label: "Funding Source" },
        { key: "funding_agency", label: "Funding Agency" },
        { key: "source_budget", label: "Source of Budget" },
        { key: "budget", label: "Budget", kind: "peso" },
      ],
    },
    {
      title: "Schedule",
      fields: [
        { key: "start_date", label: "Start Date", kind: "date" },
        { key: "end_date", label: "End Date", kind: "date" },
      ],
    },
  ],
  /* Wizard step titles — the final "Review" step is generated by the modal. */
  createStepTitles: ["Identification", "Project Details", "Funding & Schedule", "Review"],
  createFields: [
    {
      key: "year",
      label: "Year",
      type: "number",
      required: true,
      defaultValue: new Date().getFullYear(),
      step: 1,
    },
    {
      key: "classification",
      label: "Classification",
      type: "select",
      options: RE_CLASSIFICATIONS,
      required: true,
      step: 1,
    },
    {
      key: "title",
      label: "Project Title",
      type: "text",
      required: true,
      colSpan: 2,
      placeholder: "e.g. Community-based Mangrove Rehabilitation Program",
      step: 1,
    },
    {
      key: "category",
      label: "Category / Modality",
      type: "select",
      /* Options follow the chosen classification; the union list is the
         fallback until one is picked. */
      options: CATEGORY_OPTIONS,
      optionsBy: { field: "classification", map: RE_CATEGORIES },
      step: 1,
    },
    {
      key: "research_agenda",
      label: "Research Agenda / Thrust",
      type: "text",
      step: 2,
    },
    {
      key: "objectives",
      label: "Objectives",
      type: "list",
      colSpan: 2,
      help: "Separate each objective with a comma.",
      step: 2,
    },
    {
      key: "beneficiaries",
      label: "Beneficiaries / Target Sectors",
      type: "list",
      colSpan: 2,
      step: 2,
    },
    { key: "partner_agency", label: "Partner Agency", type: "text", step: 2 },
    {
      key: "delivery_site",
      label: "Delivery Site / Location",
      type: "text",
      step: 2,
    },
    {
      key: "expected_outputs",
      label: "Expected Outputs",
      type: "list",
      colSpan: 2,
      step: 2,
    },
    {
      key: "funding_source",
      label: "Funding Source",
      type: "select",
      options: RE_FUNDING_SOURCES,
      step: 3,
    },
    { key: "funding_agency", label: "Funding Agency", type: "text", step: 3 },
    { key: "budget", label: "Budget (PHP)", type: "number", step: 3 },
    { key: "source_budget", label: "Source of Budget", type: "text", step: 3 },
    { key: "start_date", label: "Start Date", type: "date", step: 3 },
    { key: "end_date", label: "End Date", type: "date", step: 3 },
  ],
};

export default function ResearchExtensionProjectsContent() {
  return <ProjectWorkspace config={CONFIG} />;
}
