"use client";

import ProjectWorkspace from "../components/ProjectWorkspace";
import { COLLEGES } from "@/lib/colleges";
import {
  ACADEMIC_PROJECT_TYPES,
  ACADEMIC_STATUSES,
  SEMESTERS,
} from "@/lib/projectModules";

/* Academic monitoring page — configuration for the shared ProjectWorkspace. */

const BADGE_CLASSES = {
  "Curriculum Development": "bg-blue-100 text-blue-700",
  "Instructional Materials": "bg-violet-100 text-violet-700",
  "Accreditation (AACCUP/ISO)": "bg-amber-100 text-amber-700",
  "Faculty Development": "bg-emerald-100 text-emerald-700",
  "Student Development": "bg-cyan-100 text-cyan-700",
  "Instruction / Pedagogy": "bg-rose-100 text-rose-700",
  Others: "bg-gray-100 text-gray-700",
};

const CONFIG = {
  title: "Academic Projects",
  subtitle:
    "Monitor instructional, curricular, and accreditation projects filed by the colleges.",
  apiBase: "/api/academic-project",
  badgeField: "project_type",
  badgeClasses: BADGE_CLASSES,
  badgeLabel: "Project Type",
  statuses: ACADEMIC_STATUSES,
  budgetField: "budget",
  showLeader: false,
  emptyHint:
    "Create the first academic project to start monitoring it here.",
  createDefaults: {},
  filters: [
    { key: "college", label: "College", options: COLLEGES },
    { key: "semester", label: "Semester", options: SEMESTERS },
  ],
  detailSections: [
    {
      title: "Program Information",
      fields: [
        { key: "college", label: "College" },
        { key: "programs", label: "Programs", kind: "array" },
        { key: "semester", label: "Semester" },
        { key: "target_participants", label: "Target Participants" },
        { key: "objectives", label: "Objectives", kind: "array" },
        { key: "expected_outputs", label: "Expected Outputs", kind: "array" },
        { key: "partner_agency", label: "Partner Agency" },
        {
          key: "responsible_office",
          label: "Responsible Office",
          kind: "array",
        },
      ],
    },
    {
      title: "Funding",
      fields: [
        { key: "budget", label: "Budget", kind: "peso" },
        { key: "source_budget", label: "Source of Budget" },
      ],
    },
    {
      title: "Schedule",
      fields: [
        { key: "start_date", label: "Start Date", kind: "date" },
        { key: "end_date", label: "End Date", kind: "date" },
      ],
    },
  ],
  /* Wizard step titles — the final "Review" step is generated by the modal. */
  createStepTitles: ["Identification", "Program Details", "Funding & Schedule", "Review"],
  createFields: [
    {
      key: "year",
      label: "Year",
      type: "number",
      required: true,
      defaultValue: new Date().getFullYear(),
      step: 1,
    },
    {
      key: "project_type",
      label: "Project Type",
      type: "select",
      options: ACADEMIC_PROJECT_TYPES,
      required: true,
      step: 1,
    },
    {
      key: "title",
      label: "Project Title",
      type: "text",
      required: true,
      colSpan: 2,
      placeholder: "e.g. Outcome-based Curriculum Review for BSIT",
      step: 1,
    },
    {
      key: "college",
      label: "College",
      type: "select",
      options: COLLEGES,
      required: true,
      step: 1,
    },
    {
      key: "programs",
      label: "Programs",
      type: "list",
      help: "Separate each program with a comma.",
      step: 2,
    },
    {
      key: "semester",
      label: "Semester",
      type: "select",
      options: SEMESTERS,
      step: 2,
    },
    {
      key: "target_participants",
      label: "Target Participants",
      type: "number",
      step: 2,
    },
    {
      key: "objectives",
      label: "Objectives",
      type: "list",
      colSpan: 2,
      help: "Separate each objective with a comma.",
      step: 2,
    },
    {
      key: "expected_outputs",
      label: "Expected Outputs",
      type: "list",
      colSpan: 2,
      step: 2,
    },
    { key: "partner_agency", label: "Partner Agency", type: "text", step: 2 },
    { key: "budget", label: "Budget (PHP)", type: "number", step: 3 },
    { key: "source_budget", label: "Source of Budget", type: "text", step: 3 },
    { key: "start_date", label: "Start Date", type: "date", step: 3 },
    { key: "end_date", label: "End Date", type: "date", step: 3 },
  ],
};

export default function AcademicProjectsContent() {
  return <ProjectWorkspace config={CONFIG} />;
}
